Check subcommand and tests

diff --git a/bin/check b/bin/check
--- a/bin/check
+++ b/bin/check
@@ -3,19 +3,46 @@
 package="$1"
 os="$(uname -s)"
 
-# Check package subcommand
-check_command=$(yq ".packages.$package.$os.check" < "$yaml_file")
-
-if [ -z "$check_command" ]; then
-    echo "'packages.$package.$os.check' entry not found in '$yaml_file'."
+# Validate if package is defined
+if ! output=$(yq ".packages.$package" < "$yaml_file") || [ -z "$output" ] || [ "$output" = "null" ]; then
+    echo "Package '$package' is not defined in '$yaml_file'."
     exit 1
 fi
 
-if eval "$check_command"; then
-    echo "Package '$package' is installed.";
+# Validate if OS is defined
+if ! output=$(yq ".packages.$package.$os" < "$yaml_file") || [ -z "$output" ] || [ "$output" = "null" ]; then
+    echo "Package's '$package' OS '$os' is not defined in '$yaml_file'."
+    exit 1
+fi
+
+# Validate if 'check' is defined
+if ! output=$(yq ".packages.$package.$os.check" < "$yaml_file") || [ -z "$output" ] || [ "$output" = "null" ]; then
+    echo "Missing 'check' entry on 'packages.$package.$os' in '$yaml_file'."
+    exit 1
+fi
+
+# Get arguments
+s_flag=false
+
+while [ "$#" -gt 0 ]; do
+    case "$1" in
+        -s)
+            s_flag=true
+            ;;
+        *)
+            ;;
+    esac
+    shift 
+done
+
+# Check package subcommand
+check_command=$(yq ".packages.$package.$os.check" < "$yaml_file")
+
+if eval "$check_command" >/dev/null 2>&1; then
+    ! $s_flag && echo "Package '$package' is installed on $os.";
     exit 0
 else
-    echo "Package '$package' is not installed on $os.";
+    ! $s_flag && echo "Package '$package' is not installed on $os.";
     exit 1
 fi
 
