Always show install command output

diff --git a/scripts/install b/scripts/install
--- a/scripts/install
+++ b/scripts/install
@@ -107,8 +107,8 @@ install_package() {
     if [ "$install" = "null" ]; then install=""; fi
 
     # if ! install_output=$(eval "$install" 2>&1); then 
-    if ! install_output=$(eval "$install"); then 
-        ! $s_flag && echo "Failed installing package '$package'. Error: $install_output"
+    if ! eval "$install"; then 
+        ! $s_flag && echo "Failed installing package '$package'."
 
         if [[ "$i_flag" = true ]]; then
             ! $s_flag && echo "Package '$package' has validation errors, ignoring."
