Make install script work on MacOS

diff --git a/scripts/install-dfm b/scripts/install-dfm
--- a/scripts/install-dfm
+++ b/scripts/install-dfm
@@ -32,16 +32,16 @@ case "$os_name" in
         fi
         ;;
     Darwin)
-        if ! command -v yq &>/dev/null; then
-            if ! command -v brew &>/dev/null; then
-                echo "Installing Homebrew..."
+        if ! command -v brew &>/dev/null; then
+            echo "Installing Homebrew..."
 
-                if ! (/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"); then
-                    echo "Error installing Homebrew. Aborting."
-                    exit 1
-                fi
+            if ! (/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"); then
+                echo "Error installing Homebrew. Aborting."
+                exit 1
             fi
+        fi
 
+        if ! command -v yq &>/dev/null; then
             echo "Installing yq..."
             
             if ! (brew install yq); then
@@ -49,6 +49,8 @@ case "$os_name" in
                 exit 1
             fi
         fi
+
+
         ;;
     *)
         echo "Unsupported OS: $os_name"
