Check for errors in sync command

diff --git a/scripts/sync b/scripts/sync
--- a/scripts/sync
+++ b/scripts/sync
@@ -8,9 +8,32 @@ commit="${machine_name}-${os}-${username}-${unixtime}"
 
 cd $DFM_DOTFILES
 
-git stash 
-git pull
-git stash pop
-git add -A
-git commit -m "[push] $commit"
-git push
+if ! git stash; then
+    echo "Error when stashing changes, aborting."
+    exit 1
+fi
+
+if ! git pull; then
+    echo "Error when pulling changes, aborting."
+    exit 1
+fi
+
+if ! git stash pop; then
+    echo "Error when popping the stash, aborting."
+    exit 1
+fi
+
+if ! git add -A; then
+    echo "Error when staging changes, aborting."
+    exit 1
+fi
+
+if ! git commit -m "[push] $commit"; then
+    echo "Error when committing changes, aborting."
+    exit 1
+fi
+
+if ! git push; then
+    echo "Error when pushing commit, aborting."
+    exit 1
+fi
